services:

    threadlabs.open_weather_map.api:
        class: ThreadLabs\OpenWeatherMapBundle\Api\OpenWeatherMap
        arguments:
            - '@threadlabs.open_weather_map.client'
            - '%threadlabs.open_weather_map.api_id%'

    threadlabs.open_weather_map.client:
        class:  GuzzleHttp\Client